title: AUCTF - Ashland University Capture the Flag
description: The official website for Ashland Universities Capture the Flag event.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman